version: "3.3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin123
    ports:
      # published only for SQL Adminer
      - 5432:5432
    networks:
      - migration

networks:
  migration:
    external: true