runtime: java
env: flex
service: 'agent'
threadsafe: True

resources:
  memory_gb: 4

env_variables:
  'ENDPOINTS_SERVICE_NAME': 'agent.endpoints.c-toolkit.cloud.goog'

handlers:
- url: /.*
  script: this field is required, but ignored

health_check:
  enable_health_check: False
