version: "3.3"
services:
  ctoolkit-agent-sql:
    image: turnonline/ctoolkit-agent-sql:0.3-SNAPSHOT
    ports:
      - 8080:8080
      - 4040:4040
    hostname: ctoolkit-agent-sql
    networks:
      - migration
    environment:
      # JAVA_OPTS: -DjdbcUrl=jdbc:postgresql://postgres:5432/root -DjdbcUsername=root -DjdbcPassword=admin123 -DjdbcDriver=org.postgresql.Driver -DmigrationTargetAgent=ELASTICSEARCH -DmigrationTargetAgentUrl=http://ctoolkit-agent-elasticsearch:8080
      # JAVA_OPTS: -DjdbcUrl=jdbc:mysql://mysql:3306 -DjdbcUsername=root -DjdbcPassword=admin123 -DjdbcDriver=com.mysql.cj.jdbc.Driver -DmigrationTargetAgent=ELASTICSEARCH -DmigrationTargetAgentUrl=http://ctoolkit-agent-elasticsearch:8080
       JAVA_OPTS: -DjdbcUrl=jdbc:postgresql://postgres:5432/root -DjdbcUsername=root -DjdbcPassword=admin123 -DjdbcDriver=org.postgresql.Driver -DmigrationTargetAgent=MONGO -DmigrationTargetAgentUrl=http://ctoolkit-agent-mongo:8080
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 1024m
        reservations:
          memory: 1024m

networks:
  migration:
    external: true