version: "3.3"
services:
  flink-job-manager:
    image: flink
    ports:
      - 8191:8081
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-job-manager
    networks:
      - migration

  flink-task-manager:
    image: flink
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-job-manager
    networks:
      - migration

networks:
  migration:
    external: true