micronaut:
  application:
    name: ctoolkit-agent-sql
  server:
    port: 8080
  http:
    client:
      read-timeout: 60s

endpoints:
  routes:
    enabled: true
    sensitive: false
  health:
    details-visible: ANONYMOUS